CREATE DATABASE HOSPITALIE_OLAP
GO
USE HOSPITALIE_OLAP
CREATE TABLE DOCTORDIMENSION (
 DOCTORCODE INT PRIMARY KEY IDENTITY (1, 1),
 DOCTORID INT,
 DOCTORNAME VARCHAR(100),
 DOCTORDOB DATE,
 DOCTORADDRESS VARCHAR(100),
 DOCTORSALARY BIGINT,
 VALIDFROM DATETIME,
 VALIDTO DATETIME
)
CREATE TABLE MEDICINEDIMENSION(
 MEDICINECODE INT PRIMARY KEY IDENTITY (1, 1),
 MEDICINEID INT NOT NULL,
 MEDICINENAME VARCHAR(100) NOT NULL,
 MEDICINESELLINGPRICE BIGINT NOT NULL,
 MEDICINEBUYINGPRICE BIGINT NOT NULL,
 MEDICINEEXPIREDDATE DATE NOT NULL
)
CREATE TABLE STAFFDIMENSION (
 STAFFCODE INT PRIMARY KEY IDENTITY (1, 1),
 STAFFID INT,
 STAFFNAME VARCHAR(100),
 STAFFDOB DATE,
 STAFFADDRESS VARCHAR(100),
 STAFFSALARY BIGINT,
 VALIDFROM DATETIME,
 VALIDTO DATETIME
)
CREATE TABLE CUSTOMERDIMENSION (
 CUSTOMERCODE INT PRIMARY KEY IDENTITY (1, 1),
 CUSTOMERID INT,
 CUSTOMERNAME VARCHAR(100),
 CUSTOMERGENDER VARCHAR(7),
 CUSTOMERADDRESS VARCHAR(100)
)
CREATE TABLE BENEFITDIMENSION (
 BENEFITCODE INT PRIMARY KEY IDENTITY (1, 1),
 BENEFITID INT,
 BENEFITNAME VARCHAR(100),
 BENEFITPRICE BIGINT,
 VALIDFROM DATETIME,
 VALIDTO DATETIME
)
CREATE TABLE TREATMENTDIMENSION (
 TREATMENTCODE INT PRIMARY KEY IDENTITY (1, 1),
 TREATMENTID INT,
 TREATMENTNAME VARCHAR(100),
 TREATMENTPRICE BIGINT,
 VALIDFROM DATETIME,
 VALIDTO DATETIME
)
CREATE TABLE DISTRIBUTORDIMENSION (
 DISTRIBUTORCODE INT PRIMARY KEY IDENTITY (1, 1),
 DISTRIBUTORID INT,
 DISTRIBUTORNAME VARCHAR(100),
 DISTRIBUTORADDRESS VARCHAR(100),
 DISTRIBUTORPHONE VARCHAR(15)
)
CREATE TABLE TIMEDIMENSION (
 TIMECODE INT PRIMARY KEY IDENTITY (1, 1),
 [DATE] DATE,
 [DAY] INT,
 [MONTH] INT,
 [QUARTER] INT,
 [YEAR] INT
)
CREATE TABLE SALESFACT (
 MEDICINECODE INT,
 STAFFCODE INT,
 CUSTOMERCODE INT,
 TIMECODE INT,
 TOTALSALESEARNING BIGINT,
 TOTALMEDICINESOLD BIGINT
)
CREATE TABLE PURCHASEFACT (
 MEDICINECODE INT,
 STAFFCODE INT,
 DISTRIBUTORCODE INT,
 TIMECODE INT,
 TOTALPURCHASECOST BIGINT
)
CREATE TABLE SUBSCRIPTIONFACT (
 CUSTOMERCODE INT,
 STAFFCODE INT,
 BENEFITCODE INT,
 TOTALSUBSCRIPTIONEARNING BIGINT,
 TOTALSUBSCRIBERCOUNT BIGINT
)
CREATE TABLE SERVICEFACT (
 CUSTOMERCODE INT,
 TREATMENTCODE INT,
 DOCTORCODE INT,
 TIMECODE INT,
 TOTALSERVICEEARNING BIGINT,
 TOTALDOCTORS BIGINT
)
CREATE TABLE FILTERTIMESTAMP (
 TABLENAME VARCHAR(100) PRIMARY KEY,
 LASTETL DATETIME
)